/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef TEST_H
#define TEST_H

#ifdef _WIN32
#define TEST_EXPORT_FUNC __declspec(dllexport)
#else
#define TEST_EXPORT_FUNC
#endif

#include <string>

namespace test {
    class Greeter {
        public:
        std::string TEST_EXPORT_FUNC greeting();
    };
}

#endif
