/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_hpopov_daqhats_TCHatId */

#ifndef _Included_com_github_hpopov_daqhats_TCHatId
#define _Included_com_github_hpopov_daqhats_TCHatId
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_hpopov_daqhats_TCHatId
 * Method:    findConnectedMcc134HatsAddresses
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_github_hpopov_daqhats_TCHatId_findConnectedMcc134HatsAddresses
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
