/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_hpopov_daqhats_JavaServer */

#ifndef _Included_com_github_hpopov_daqhats_JavaServer
#define _Included_com_github_hpopov_daqhats_JavaServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_hpopov_daqhats_JavaServer
 * Method:    calculatevolume_in_cplusplus
 * Signature: (Lcom/github/hpopov/daqhats/RequestData;)Lcom/github/hpopov/daqhats/ResponseData;
 */
JNIEXPORT jobject JNICALL Java_com_github_hpopov_daqhats_JavaServer_calculatevolume_1in_1cplusplus
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
